os: unstable
skip_tags: true

install:
#  - set QTDIR=C:\Qt\5.6\mingw49_32
  - set QTDIR=C:\Qt\5.7\mingw53_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
  - set RELEASE_PATH=appveyor\release

build_script:
    - cd .\AurebeshTranslator
    - dir
    # we need to modify that to make it running on AppVeyor
    - sed -i "s/CONFIG += c++11/QMAKE_CXXFLAGS += -std=gnu++0x/g" AurebeshTranslator.pro
    - "echo #define RELEASE \"AppVeyor\" > release.h"
    # setting the build number in the header file
    - "echo #define BUILD %APPVEYOR_BUILD_NUMBER% > build_number.h"
    - qmake AurebeshTranslator.pro -r -spec win32-g++
    - mingw32-make
    - md ..\%RELEASE_PATH%
    - copy release\AurebeshTranslator.exe ..\%RELEASE_PATH%
    - cd ..\%RELEASE_PATH%
    # fetching dependencies of QT app
    # http://doc.qt.io/qt-5/windows-deployment.html
    - windeployqt --release AurebeshTranslator.exe

    - cd ..\Tests\Test
    # we need to modify that to make it running on AppVeyor
    - sed -i "s/CONFIG += c++11/QMAKE_CXXFLAGS += -std=gnu++0x/g" Test.pro
    - "echo #define RELEASE \"AppVeyor\" > release.h"
    - qmake -project "QT += testlib"
    - qmake Test.pro
    - mingw32-make
    - dir
    #-  .\release\Test.exe

artifacts:
  # pushing entire folder as a zip archive
  - path: appveyor\release
    name: AurebeshTranslator