install:
    - set QTDIR=C:\Qt\5.7\mingw53_32
    - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
build_script:
    - cd .\AurebeshTranslator
    - qmake AurebeshTranslator.pro
    - mingw32-make
    - cd ..\Tests\Test
    - qmake -project "QT += testlib"
    - qmake 
    - mingw32-make
    - dir